name: Run Python Script

on:
  schedule:
    - cron: '0 19 * * *' # Runs at 7 PM UTC = 5 AM Sydney Time
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug environment variables before running fetch_data.py
        env:
          STORM_API: ${{ secrets.STORM_API }}
        run: env | grep STORM_API || echo "STORM_API not set"
      
      - name: Fetch latest API data
        env:
          STORM_API: ${{ secrets.STORM_API }}
        run: python fetch_data.py
      
      - name: Configure Git user
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"

      - name: Commit changes
        run: git commit -a -m "Latest API data"


      - name: Push changes
        run: git push
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
