name: Run Python Script

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Fetch latest API data
        env:
          API_KEY: ${{ secrets.STORM.API }}
        run: python fetch_data.py

      - name: Set up authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Roifine/ocean-conditions-bot.git

      
      - name: Configure Git user
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"

      - name: Commit changes
        run: git commit -a -m "Latest API data"

      - name: Push changes
        run: git push
